version: "3.7"
services:
  financialService:
    image: "16bits/financial-service:0.0.1"
    container_name: "financialService"
    ports:
      - "8081:8081"
  tropicalDB:
    image: "16bits/tropicalflix_db:0.0.1"
    container_name: "tropicalflixDB"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "Tropicalflix"
    ports:
      - "3306:3306"
  tropicalflix:
    depends_on:
      - financialService
      - tropicalDB
    image: "16bits/tropicalflix:0.0.1"
    container_name: "tropicalflix"
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.profiles.active":"default,mysql",
                "spring.datasource.url"  : "jdbc:mysql://tropicalflixDB:3306/Tropicalflix?createDatabaseIfNotExist=true"
            }'
    ports:
      - "8080:8080"