spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Tropicalflix
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  jpa:
    show-sql: false
    defer-datasource-initialization: false