create table actors
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table genres
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table movies
(
    id            bigint generated by default as identity,
    title         varchar(255),
    overview      varchar(1000),
    minutes       integer   not null,
    rating        float(53) not null,
    released_year integer   not null,
    director      varchar(255),
    primary key (id)
);
create table movies_actors
(
    actor_id bigint not null,
    movie_id bigint not null,
    primary key (actor_id, movie_id)
);
create table movies_genres
(
    genre_id bigint not null,
    movie_id bigint not null,
    primary key (genre_id, movie_id)
);
alter table if exists movies_actors add constraint FKlexe564x1fi4ssje5wcuii3v2 foreign key (actor_id) references actors;
alter table if exists movies_actors add constraint FKo40lc9yirox8um5poaxhw6ak0 foreign key (movie_id) references movies;

alter table if exists movies_genres add constraint FKrs5u5iygsuht2f0cag9b9h1ob foreign key (genre_id) references genres;
alter table if exists movies_genres add constraint FKk0w7fx0a7flrtafppanyup87d foreign key (movie_id) references movies;