spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:moviedb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: Tropicalflix
  sql:
    init:
      schema-locations: classpath:/database/scripts/schema.sql
      data-locations: classpath:/database/scripts/data.sql